# Generated by Django 4.2.4 on 2023-08-15 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_task_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='director_id',
            new_name='director',
        ),
    ]
