# Generated by Django 4.2.4 on 2023-08-18 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_director_id_task_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.director'),
        ),
    ]
